// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3482.robot.subsystems;

import org.usfirst.frc3482.robot.Robot;
import org.usfirst.frc3482.robot.RobotMap;
import org.usfirst.frc3482.robot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Chassis extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController backLeft = RobotMap.chassisBackLeft;
    SpeedController backRight = RobotMap.chassisBackRight;
    SpeedController frontRight = RobotMap.chassisFrontRight;
    SpeedController frontLeft = RobotMap.chassisFrontLeft;
    RobotDrive robotDrive41 = RobotMap.chassisRobotDrive41;
    Compressor compressor1 = RobotMap.chassisCompressor1;
    //IMU imu = RobotMap.gyroIMU;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    boolean inverted = false;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void invertMotors() {
    	if(!inverted) {
			robotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
			robotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, false);
			robotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
			robotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, false);
			inverted = true;
			System.out.println("YO THE MOTORS WERE JUST INVERTED, WATCH OUT MAN");
    	}
	}
    
    /*public void calibrateGyro() {
    	System.out.println("calibrating");
    	Robot.imu.initGyro();
    }
    
    public void resetGyro() {
    	System.out.println("reseting");
       	Robot.imu.reset();
    }*/
    
    public void startCompressor() {
    	//System.out.println("starting");
		compressor1.start();
	}
	public void stopCompressor() {
		compressor1.stop();
	}
    
	public void driveWithXboxController(Joystick s) {
		double leftX = s.getRawAxis(0);
		double leftY = s.getRawAxis(1);
		double rightX = s.getRawAxis(4);
		
		//System.out.println("left x: " + leftX);
		//System.out.println("y: " + leftY);
		//System.out.println("right: " + rightX);
		double deadZone = 0.2;

		if (leftX < deadZone && leftX > -deadZone) {
			leftX = 0;
		}
		if (leftY < deadZone && leftY > -deadZone) {
			leftY = 0;
		}
		if (rightX < deadZone && rightX > -deadZone) {
			rightX = 0;
		}
		
		//TODO: Gyro
		robotDrive41.mecanumDrive_Cartesian(leftX, leftY, rightX, 0);

	}
	public void driveWithJoystick(Joystick s) {
		double pi = 3.1415926;
		double leftX = s.getRawAxis(0);
		double leftY = s.getRawAxis(1);
		double twist = s.getTwist();
		double throttle = (1-s.getThrottle())/2;
		double max = .7;
		double min = .2;
		double sensitivity = 1.0;
		double deadZone = 0.125;

		if (leftX < deadZone && leftX > -deadZone) {
			leftX = 0;
		}
		if (leftY < deadZone && leftY > -deadZone) {
			leftY = 0;
		}
		if (twist < deadZone && twist > -deadZone) {
			twist = 0;
		}
		
		sensitivity = throttle*max+(1-throttle)*min;
		if(s.getRawButton(1)) {
			sensitivity = .8;
		}
		//System.out.println(sensitivity);
		
		// Thresholds for determining if currently off-balance/on-balance.
		double offBalancePitchGyroAngleThresholdDegrees = 10/2;
		double onBalancePitchGyroAngleThresholdDegrees  = 5/2;
		boolean autoBalanceMode = false;
        double curr_gyro_angle_degrees = 0;
        double pitchAngle = 0;
        
        if(Robot.imu.isConnected()) {
        	curr_gyro_angle_degrees = Robot.imu.getYaw();
        	pitchAngle = Robot.imu.getPitch();
        	//System.out.println(pitchAngle);
        }
        double curr_gyro_angle_radians = curr_gyro_angle_degrees*pi/180;
		                
		// Determine whether assisted balance mode is in effect;
		if (!autoBalanceMode && (pitchAngle >= offBalancePitchGyroAngleThresholdDegrees)) {
			autoBalanceMode = true;
		}
		else if (autoBalanceMode && (pitchAngle <= (-onBalancePitchGyroAngleThresholdDegrees))) {
			autoBalanceMode = false;
		}
		
		if(autoBalanceMode) {
			double pitchAngleRadians = pitchAngle * (3.1415926 / 180.0);
			double driveRate = Math.sin(pitchAngleRadians)*-1;
			robotDrive41.mecanumDrive_Cartesian(0, driveRate, 0, 0);
		} else {
	        double strafe = leftX;
	        double fwd = -leftY;
	        double rcw = twist;
	        
	        double temp = fwd * Math.cos( curr_gyro_angle_radians ) + strafe * Math.sin( curr_gyro_angle_radians);
	        strafe = -fwd * Math.sin( curr_gyro_angle_radians ) + strafe * Math.cos( curr_gyro_angle_radians );
	        fwd = temp;
	        
	        robotDrive41.mecanumDrive_Cartesian(strafe*sensitivity, -fwd*sensitivity, rcw*sensitivity, 0);
		}
	}
	
	//moves the robot to a location
	public void move(double moveValueY, double moveValueX, double rotateValue) {
		//robotDrive41.arcadeDrive(moveValue, rotateValue);
		robotDrive41.mecanumDrive_Cartesian(moveValueX, moveValueY, rotateValue, 0);
	}

	public void stop() {
		robotDrive41.stopMotor();
	}
	
	//sets the safety
	public void setSafety(boolean n) {
		robotDrive41.setSafetyEnabled(n);
	}

}

